#!/usr/bin/env python3
"""GPL-2.0-or-later. Emit kernel-checkable claims from the integrator certificates.

The generator is not trusted for arithmetic truth: Lean checks every emitted
identity/inequality. Source extraction and completeness of the order-condition
enumeration remain reviewed mappings, not conclusions of these Lean proofs.
"""
from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent


def fraction(data: dict) -> Fraction:
    return Fraction(int(data["numerator"]), int(data["denominator"]))


def literal(value: Fraction) -> str:
    return f"({value.numerator} / {value.denominator})"


def sum_expr(values: list[str]) -> str:
    return "(" + " + ".join(values or ["0"]) + ")"


def product_expr(values: list[str]) -> str:
    return "(" + " * ".join(values or ["1"]) + ")"


def parse_tree(text: str) -> list:
    """Parse only the source report's bracket-tree grammar, including [[][]]."""
    position = 0

    def node() -> list:
        nonlocal position
        if position >= len(text) or text[position] != "[":
            raise ValueError("Expected opening bracket in rooted tree")
        position += 1
        children = []
        while position < len(text) and text[position] == "[":
            children.append(node())
        if position >= len(text) or text[position] != "]":
            raise ValueError("Expected closing bracket in rooted tree")
        position += 1
        return children

    tree = node()
    if position != len(text):
        raise ValueError("Unexpected trailing rooted-tree syntax")
    return tree


def tree_parameters(tree: list) -> tuple[int, int]:
    children = [tree_parameters(child) for child in tree]
    order = 1 + sum(n for n, _ in children)
    gamma = order
    for _, g in children:
        gamma *= g
    return order, gamma


def main() -> None:
    path = ROOT / "verification/integrator/evidence/analysis.json"
    content = path.read_bytes()
    report = json.loads(content)
    certificate = report["invisibleRhsCounterexamples"]["rkfCorrected"]
    roots = [fraction(x) for x in certificate["roots"]]
    stored_c = [fraction(x) for x in report["analyses"]["rkfStored"]["tableau"]["c"]]
    if roots != stored_c or len(roots) != 6:
        raise ValueError("RHS roots must be the six current stored RKF stage times")
    coefficients = [fraction(x) for x in certificate["ascendingPowerCoefficients"]]
    integral = fraction(certificate["integralZeroToOne"])
    out = ["import Mathlib.Analysis.Calculus.Deriv.Polynomial",
           "import Mathlib.Tactic.NormNum", "import Mathlib.Tactic.Ring", "",
           "/- GPL-2.0-or-later. Generated by generate_integrator.py.",
           "Input analysis SHA256: " + hashlib.sha256(content).hexdigest(),
           "The kernel proves a real ODE solution/counterexample and finite tableau identities.",
           "It does not infer the C implementation from the source mapping. -/",
           "set_option maxHeartbeats 8000000", "set_option maxRecDepth 8192", "",
           "namespace FindOrbIntegrator", "noncomputable section", "open Polynomial", ""]
    theorems: list[str] = []

    def theorem(name: str, statement: str, proof: str) -> None:
        out.extend([f"theorem {name} {statement} := by", proof, ""])
        theorems.append("FindOrbIntegrator." + name)

    rhs = product_expr([f"(t - {literal(c)})^2" for c in roots])
    primitive = sum_expr([f"C ({literal(c / (i + 1))} : ℝ) * X^{i + 1}"
                          for i, c in enumerate(coefficients) if c])
    out.extend([f"def rhs (t : ℝ) : ℝ := {rhs}",
                f"def exactSolution : Polynomial ℝ := {primitive}", ""])
    theorem("solution_derivative", "(t : ℝ) :\n    HasDerivAt (fun x => exactSolution.eval x) (rhs t) t",
            "  have h : exactSolution.derivative.eval t = rhs t := by\n"
            "    norm_num [exactSolution, rhs, derivative_mul]\n    ring\n"
            "  simpa only [h] using exactSolution.hasDerivAt t")
    theorem("solution_initial", ": exactSolution.eval 0 = 0", "  norm_num [exactSolution]")
    theorem("solution_endpoint", f": exactSolution.eval 1 = ({literal(integral)} : ℝ)",
            "  norm_num [exactSolution]")
    theorem("solution_nonzero", ": 0 < exactSolution.eval 1", "  rw [solution_endpoint]\n  norm_num")
    for i, c in enumerate(roots):
        theorem(f"invisible_stage_{i}", f": rhs ({literal(c)} : ℝ) = 0", "  norm_num [rhs]")
    weighted = sum_expr([f"w{i} * rhs ({literal(c)} : ℝ)" for i, c in enumerate(roots)])
    theorem("every_weighted_estimate_zero", "(w0 w1 w2 w3 w4 w5 : ℝ) : " + weighted + " = 0",
            "  rw [" + ", ".join(f"invisible_stage_{i}" for i in range(6)) + "]\n  ring")

    # Independent finite arithmetic checks of the exact rational tableau. The
    # child-tree structure is reflected into the stated stage equations, rather
    # than merely asserting the generator's precomputed residual is zero.
    ideal = report["analyses"]["rkfIdeal"]
    tableau = ideal["tableau"]
    matrix = [[fraction(x) for x in row] for row in tableau["A"]]
    conditions = [c for c in ideal["autonomousRootedTreeConditions"] if c["order"] <= 5]
    if len(conditions) != 17:
        raise ValueError("Expected all 17 rooted-tree conditions through order five")
    tree_key = lambda tree: json.dumps(tree, separators=(",", ":"))
    known = {tree_key(parse_tree(c["tree"])): c for c in conditions}
    if len(known) != 17:
        raise ValueError("Duplicated rooted-tree condition")
    for index, condition in enumerate(conditions):
        tree = parse_tree(condition["tree"])
        if tree_parameters(tree) != (condition["order"], condition["gamma"]):
            raise ValueError("Rooted-tree order or factorial mismatch")
        stage = [fraction(x) for x in condition["stageElementaryWeights"]]
        if len(stage) != 6:
            raise ValueError("Expected six elementary weights")
        for i in range(6):
            factors = []
            for child in tree:
                child_stage = [fraction(x) for x in known[tree_key(child)]["stageElementaryWeights"]]
                factors.append(sum_expr([f"{literal(matrix[i][j])} * {literal(child_stage[j])}"
                                         for j in range(6) if matrix[i][j] and child_stage[j]]))
            theorem(f"tree_{index}_stage_{i}", f": ({product_expr(factors)} : ℚ) = {literal(stage[i])}",
                    "  norm_num")
        for key, degree in [("b", 5), ("bEmbedded", 4)]:
            if condition["order"] > degree:
                continue
            weights = [fraction(x) for x in tableau[key]]
            expr = sum_expr([f"{literal(w)} * {literal(s)}" for w, s in zip(weights, stage) if w and s])
            theorem(f"tree_{index}_{key}", f": ({expr} : ℚ) = 1 / {int(condition['gamma'])}",
                    "  norm_num")

    # Kernel-check the quantitative defect independently of its printed decimal.
    moment = report["originalPdTimeCounterexample"]
    defect = fraction(moment["defect"])
    theorem("original_pd_time_defect", f": ({literal(defect)} : ℚ) < -(1 / 6)", "  norm_num")
    out.extend(["end", "end FindOrbIntegrator", ""])
    out.extend("#print axioms " + name for name in theorems)
    output = HERE / "IntegratorCertificates.lean"
    output.write_text("\n".join(out) + "\n")
    (HERE / "integrator-certificate-manifest.json").write_text(json.dumps({
        "inputSHA256": hashlib.sha256(content).hexdigest(),
        "sourceSHA256": hashlib.sha256(output.read_bytes()).hexdigest(),
        "theorems": theorems,
        "scope": "Real polynomial ODE counterexample; 102 stage identities and 25 exact-rational order equalities; original PD timing-defect inequality",
        "limits": "No theorem proves the C source mapping or completeness/sufficiency of the rooted-tree enumeration; no general floating-point integrator accuracy theorem"
    }, indent=2) + "\n")
    print(f"Generated {output.relative_to(ROOT)} with {len(theorems)} theorem obligations")


if __name__ == "__main__":
    main()
