import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/- GPL-2.0-or-later. Generated by generate_integrator.py.
Input analysis SHA256: 682fb147cb12625939c78d45ec5faf644fd862916b783e37312c6507e0a93f01
The kernel proves a real ODE solution/counterexample and finite tableau identities.
It does not infer the C implementation from the source mapping. -/
set_option maxHeartbeats 8000000
set_option maxRecDepth 8192

namespace FindOrbIntegrator
noncomputable section
open Polynomial

def rhs (t : ℝ) : ℝ := ((t - (0 / 1))^2 * (t - (2001599834386887 / 9007199254740992))^2 * (t - (6004799503160661 / 18014398509481984))^2 * (t - (3 / 4))^2 * (t - (1 / 1))^2 * (t - (7505999378950827 / 9007199254740992))^2)
def exactSolution : Polynomial ℝ := (C ((24416861407417807473987004990183719951063406417057174665815203872732608222762698543267494108963 / 34175792574734561318320347298712833833643272357706444319152665725155515612490248800367393390985216) : ℝ) * X^3 + C ((-808198112585529453982076516023401405160944178882798447605462784609682078975741717876947523918325 / 68351585149469122636640694597425667667286544715412888638305331450311031224980497600734786781970432) : ℝ) * X^4 + C ((15382704076211244379773628191719268788008663480332433011297475790963465790358083237496509417715113 / 170878962873672806591601736493564169168216361788532221595763328625777578062451244001836966954926080) : ℝ) * X^5 + C ((-3462541551262915451724091850701923324521397745461514786512395550836939280251771958448817253346701 / 8543948143683640329580086824678208458410818089426611079788166431288878903122562200091848347746304) : ℝ) * X^6 + C ((17650206431887859230602607934956914323310299156063000981305200257804004832200994629893415947864673 / 14951909251446370576765151943186864802218931656496569389629291254755538080464483850160734608556032) : ℝ) * X^7 + C ((-548122794400855113575415536977355989049190873106838311940397182347785245617414365 / 237142198758023568227473377297792835283496928595231875152809132048206089502588928) : ℝ) * X^8 + C ((40470514948972119569143098128373461786607434557973404739390823785 / 13164036458569648337239753460458804039861886925068638906788872192) : ℝ) * X^9 + C ((-20040578071461186389953298399800715080819312629819 / 7307508186654514591018424163581415098279662714880) : ℝ) * X^10 + C ((5610214656417477490509181383059329 / 3569704090242693994614716226338816) : ℝ) * X^11 + C ((-56545195321429561 / 108086391056891904) : ℝ) * X^12 + C ((1 / 13) : ℝ) * X^13)

theorem solution_derivative (t : ℝ) :
    HasDerivAt (fun x => exactSolution.eval x) (rhs t) t := by
  have h : exactSolution.derivative.eval t = rhs t := by
    norm_num [exactSolution, rhs, derivative_mul]
    ring
  simpa only [h] using exactSolution.hasDerivAt t

theorem solution_initial : exactSolution.eval 0 = 0 := by
  norm_num [exactSolution]

theorem solution_endpoint : exactSolution.eval 1 = ((403936277216715363827518561565728433748210545385559334957163497148839782449406745037549358401029 / 1026299051019278876389160029380346400024307468901924522904154551726420133843082171475032823531286036480) : ℝ) := by
  norm_num [exactSolution]

theorem solution_nonzero : 0 < exactSolution.eval 1 := by
  rw [solution_endpoint]
  norm_num

theorem invisible_stage_0 : rhs ((0 / 1) : ℝ) = 0 := by
  norm_num [rhs]

theorem invisible_stage_1 : rhs ((2001599834386887 / 9007199254740992) : ℝ) = 0 := by
  norm_num [rhs]

theorem invisible_stage_2 : rhs ((6004799503160661 / 18014398509481984) : ℝ) = 0 := by
  norm_num [rhs]

theorem invisible_stage_3 : rhs ((3 / 4) : ℝ) = 0 := by
  norm_num [rhs]

theorem invisible_stage_4 : rhs ((1 / 1) : ℝ) = 0 := by
  norm_num [rhs]

theorem invisible_stage_5 : rhs ((7505999378950827 / 9007199254740992) : ℝ) = 0 := by
  norm_num [rhs]

theorem every_weighted_estimate_zero (w0 w1 w2 w3 w4 w5 : ℝ) : (w0 * rhs ((0 / 1) : ℝ) + w1 * rhs ((2001599834386887 / 9007199254740992) : ℝ) + w2 * rhs ((6004799503160661 / 18014398509481984) : ℝ) + w3 * rhs ((3 / 4) : ℝ) + w4 * rhs ((1 / 1) : ℝ) + w5 * rhs ((7505999378950827 / 9007199254740992) : ℝ)) = 0 := by
  rw [invisible_stage_0, invisible_stage_1, invisible_stage_2, invisible_stage_3, invisible_stage_4, invisible_stage_5]
  ring

theorem tree_0_stage_0 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_stage_1 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_stage_2 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_stage_3 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_stage_4 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_stage_5 : ((1) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_0_b : (((47 / 450) * (1 / 1) + (12 / 25) * (1 / 1) + (32 / 225) * (1 / 1) + (1 / 30) * (1 / 1) + (6 / 25) * (1 / 1)) : ℚ) = 1 / 1 := by
  norm_num

theorem tree_0_bEmbedded : (((1 / 9) * (1 / 1) + (9 / 20) * (1 / 1) + (16 / 45) * (1 / 1) + (1 / 12) * (1 / 1)) : ℚ) = 1 / 1 := by
  norm_num

theorem tree_1_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_1_stage_1 : ((((2 / 9) * (1 / 1))) : ℚ) = (2 / 9) := by
  norm_num

theorem tree_1_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1))) : ℚ) = (1 / 3) := by
  norm_num

theorem tree_1_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1))) : ℚ) = (3 / 4) := by
  norm_num

theorem tree_1_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1))) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_1_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1))) : ℚ) = (5 / 6) := by
  norm_num

theorem tree_1_b : (((12 / 25) * (1 / 3) + (32 / 225) * (3 / 4) + (1 / 30) * (1 / 1) + (6 / 25) * (5 / 6)) : ℚ) = 1 / 2 := by
  norm_num

theorem tree_1_bEmbedded : (((9 / 20) * (1 / 3) + (16 / 45) * (3 / 4) + (1 / 12) * (1 / 1)) : ℚ) = 1 / 2 := by
  norm_num

theorem tree_2_stage_0 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_2_stage_1 : ((((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1))) : ℚ) = (4 / 81) := by
  norm_num

theorem tree_2_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1))) : ℚ) = (1 / 9) := by
  norm_num

theorem tree_2_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1))) : ℚ) = (9 / 16) := by
  norm_num

theorem tree_2_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1))) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_2_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1))) : ℚ) = (25 / 36) := by
  norm_num

theorem tree_2_b : (((12 / 25) * (1 / 9) + (32 / 225) * (9 / 16) + (1 / 30) * (1 / 1) + (6 / 25) * (25 / 36)) : ℚ) = 1 / 3 := by
  norm_num

theorem tree_2_bEmbedded : (((9 / 20) * (1 / 9) + (16 / 45) * (9 / 16) + (1 / 12) * (1 / 1)) : ℚ) = 1 / 3 := by
  norm_num

theorem tree_3_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_3_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_3_stage_2 : ((((1 / 4) * (2 / 9))) : ℚ) = (1 / 18) := by
  norm_num

theorem tree_3_stage_3 : ((((-243 / 128) * (2 / 9) + (135 / 64) * (1 / 3))) : ℚ) = (9 / 32) := by
  norm_num

theorem tree_3_stage_4 : ((((27 / 4) * (2 / 9) + (-27 / 5) * (1 / 3) + (16 / 15) * (3 / 4))) : ℚ) = (1 / 2) := by
  norm_num

theorem tree_3_stage_5 : ((((-5 / 16) * (2 / 9) + (13 / 16) * (1 / 3) + (4 / 27) * (3 / 4) + (5 / 144) * (1 / 1))) : ℚ) = (25 / 72) := by
  norm_num

theorem tree_3_b : (((12 / 25) * (1 / 18) + (32 / 225) * (9 / 32) + (1 / 30) * (1 / 2) + (6 / 25) * (25 / 72)) : ℚ) = 1 / 6 := by
  norm_num

theorem tree_3_bEmbedded : (((9 / 20) * (1 / 18) + (16 / 45) * (9 / 32) + (1 / 12) * (1 / 2)) : ℚ) = 1 / 6 := by
  norm_num

theorem tree_4_stage_0 : (((0) * (0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_4_stage_1 : ((((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1))) : ℚ) = (8 / 729) := by
  norm_num

theorem tree_4_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1))) : ℚ) = (1 / 27) := by
  norm_num

theorem tree_4_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1))) : ℚ) = (27 / 64) := by
  norm_num

theorem tree_4_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1))) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_4_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1))) : ℚ) = (125 / 216) := by
  norm_num

theorem tree_4_b : (((12 / 25) * (1 / 27) + (32 / 225) * (27 / 64) + (1 / 30) * (1 / 1) + (6 / 25) * (125 / 216)) : ℚ) = 1 / 4 := by
  norm_num

theorem tree_4_bEmbedded : (((9 / 20) * (1 / 27) + (16 / 45) * (27 / 64) + (1 / 12) * (1 / 1)) : ℚ) = 1 / 4 := by
  norm_num

theorem tree_5_stage_0 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_5_stage_1 : ((((2 / 9) * (1 / 1)) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_5_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 4) * (2 / 9))) : ℚ) = (1 / 54) := by
  norm_num

theorem tree_5_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((-243 / 128) * (2 / 9) + (135 / 64) * (1 / 3))) : ℚ) = (27 / 128) := by
  norm_num

theorem tree_5_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((27 / 4) * (2 / 9) + (-27 / 5) * (1 / 3) + (16 / 15) * (3 / 4))) : ℚ) = (1 / 2) := by
  norm_num

theorem tree_5_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((-5 / 16) * (2 / 9) + (13 / 16) * (1 / 3) + (4 / 27) * (3 / 4) + (5 / 144) * (1 / 1))) : ℚ) = (125 / 432) := by
  norm_num

theorem tree_5_b : (((12 / 25) * (1 / 54) + (32 / 225) * (27 / 128) + (1 / 30) * (1 / 2) + (6 / 25) * (125 / 432)) : ℚ) = 1 / 8 := by
  norm_num

theorem tree_5_bEmbedded : (((9 / 20) * (1 / 54) + (16 / 45) * (27 / 128) + (1 / 12) * (1 / 2)) : ℚ) = 1 / 8 := by
  norm_num

theorem tree_6_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_6_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_6_stage_2 : ((((1 / 4) * (4 / 81))) : ℚ) = (1 / 81) := by
  norm_num

theorem tree_6_stage_3 : ((((-243 / 128) * (4 / 81) + (135 / 64) * (1 / 9))) : ℚ) = (9 / 64) := by
  norm_num

theorem tree_6_stage_4 : ((((27 / 4) * (4 / 81) + (-27 / 5) * (1 / 9) + (16 / 15) * (9 / 16))) : ℚ) = (1 / 3) := by
  norm_num

theorem tree_6_stage_5 : ((((-5 / 16) * (4 / 81) + (13 / 16) * (1 / 9) + (4 / 27) * (9 / 16) + (5 / 144) * (1 / 1))) : ℚ) = (125 / 648) := by
  norm_num

theorem tree_6_b : (((12 / 25) * (1 / 81) + (32 / 225) * (9 / 64) + (1 / 30) * (1 / 3) + (6 / 25) * (125 / 648)) : ℚ) = 1 / 12 := by
  norm_num

theorem tree_6_bEmbedded : (((9 / 20) * (1 / 81) + (16 / 45) * (9 / 64) + (1 / 12) * (1 / 3)) : ℚ) = 1 / 12 := by
  norm_num

theorem tree_7_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_7_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_7_stage_2 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_7_stage_3 : ((((135 / 64) * (1 / 18))) : ℚ) = (15 / 128) := by
  norm_num

theorem tree_7_stage_4 : ((((-27 / 5) * (1 / 18) + (16 / 15) * (9 / 32))) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_7_stage_5 : ((((13 / 16) * (1 / 18) + (4 / 27) * (9 / 32) + (5 / 144) * (1 / 2))) : ℚ) = (5 / 48) := by
  norm_num

theorem tree_7_b : (((32 / 225) * (15 / 128) + (6 / 25) * (5 / 48)) : ℚ) = 1 / 24 := by
  norm_num

theorem tree_7_bEmbedded : (((16 / 45) * (15 / 128)) : ℚ) = 1 / 24 := by
  norm_num

theorem tree_8_stage_0 : (((0) * (0) * (0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_8_stage_1 : ((((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1))) : ℚ) = (16 / 6561) := by
  norm_num

theorem tree_8_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1))) : ℚ) = (1 / 81) := by
  norm_num

theorem tree_8_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1))) : ℚ) = (81 / 256) := by
  norm_num

theorem tree_8_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1))) : ℚ) = (1 / 1) := by
  norm_num

theorem tree_8_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1))) : ℚ) = (625 / 1296) := by
  norm_num

theorem tree_8_b : (((12 / 25) * (1 / 81) + (32 / 225) * (81 / 256) + (1 / 30) * (1 / 1) + (6 / 25) * (625 / 1296)) : ℚ) = 1 / 5 := by
  norm_num

theorem tree_9_stage_0 : (((0) * (0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_9_stage_1 : ((((2 / 9) * (1 / 1)) * ((2 / 9) * (1 / 1)) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_9_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 4) * (2 / 9))) : ℚ) = (1 / 162) := by
  norm_num

theorem tree_9_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((-243 / 128) * (2 / 9) + (135 / 64) * (1 / 3))) : ℚ) = (81 / 512) := by
  norm_num

theorem tree_9_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((27 / 4) * (2 / 9) + (-27 / 5) * (1 / 3) + (16 / 15) * (3 / 4))) : ℚ) = (1 / 2) := by
  norm_num

theorem tree_9_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((-5 / 16) * (2 / 9) + (13 / 16) * (1 / 3) + (4 / 27) * (3 / 4) + (5 / 144) * (1 / 1))) : ℚ) = (625 / 2592) := by
  norm_num

theorem tree_9_b : (((12 / 25) * (1 / 162) + (32 / 225) * (81 / 512) + (1 / 30) * (1 / 2) + (6 / 25) * (625 / 2592)) : ℚ) = 1 / 10 := by
  norm_num

theorem tree_10_stage_0 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_10_stage_1 : ((((2 / 9) * (1 / 1)) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_10_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * ((1 / 4) * (4 / 81))) : ℚ) = (1 / 243) := by
  norm_num

theorem tree_10_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((-243 / 128) * (4 / 81) + (135 / 64) * (1 / 9))) : ℚ) = (27 / 256) := by
  norm_num

theorem tree_10_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((27 / 4) * (4 / 81) + (-27 / 5) * (1 / 9) + (16 / 15) * (9 / 16))) : ℚ) = (1 / 3) := by
  norm_num

theorem tree_10_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((-5 / 16) * (4 / 81) + (13 / 16) * (1 / 9) + (4 / 27) * (9 / 16) + (5 / 144) * (1 / 1))) : ℚ) = (625 / 3888) := by
  norm_num

theorem tree_10_b : (((12 / 25) * (1 / 243) + (32 / 225) * (27 / 256) + (1 / 30) * (1 / 3) + (6 / 25) * (625 / 3888)) : ℚ) = 1 / 15 := by
  norm_num

theorem tree_11_stage_0 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_11_stage_1 : ((((2 / 9) * (1 / 1)) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_11_stage_2 : ((((1 / 12) * (1 / 1) + (1 / 4) * (1 / 1)) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_11_stage_3 : ((((69 / 128) * (1 / 1) + (-243 / 128) * (1 / 1) + (135 / 64) * (1 / 1)) * ((135 / 64) * (1 / 18))) : ℚ) = (45 / 512) := by
  norm_num

theorem tree_11_stage_4 : ((((-17 / 12) * (1 / 1) + (27 / 4) * (1 / 1) + (-27 / 5) * (1 / 1) + (16 / 15) * (1 / 1)) * ((-27 / 5) * (1 / 18) + (16 / 15) * (9 / 32))) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_11_stage_5 : ((((65 / 432) * (1 / 1) + (-5 / 16) * (1 / 1) + (13 / 16) * (1 / 1) + (4 / 27) * (1 / 1) + (5 / 144) * (1 / 1)) * ((13 / 16) * (1 / 18) + (4 / 27) * (9 / 32) + (5 / 144) * (1 / 2))) : ℚ) = (25 / 288) := by
  norm_num

theorem tree_11_b : (((32 / 225) * (45 / 512) + (6 / 25) * (25 / 288)) : ℚ) = 1 / 30 := by
  norm_num

theorem tree_12_stage_0 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_12_stage_1 : (((0) * (0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_12_stage_2 : ((((1 / 4) * (2 / 9)) * ((1 / 4) * (2 / 9))) : ℚ) = (1 / 324) := by
  norm_num

theorem tree_12_stage_3 : ((((-243 / 128) * (2 / 9) + (135 / 64) * (1 / 3)) * ((-243 / 128) * (2 / 9) + (135 / 64) * (1 / 3))) : ℚ) = (81 / 1024) := by
  norm_num

theorem tree_12_stage_4 : ((((27 / 4) * (2 / 9) + (-27 / 5) * (1 / 3) + (16 / 15) * (3 / 4)) * ((27 / 4) * (2 / 9) + (-27 / 5) * (1 / 3) + (16 / 15) * (3 / 4))) : ℚ) = (1 / 4) := by
  norm_num

theorem tree_12_stage_5 : ((((-5 / 16) * (2 / 9) + (13 / 16) * (1 / 3) + (4 / 27) * (3 / 4) + (5 / 144) * (1 / 1)) * ((-5 / 16) * (2 / 9) + (13 / 16) * (1 / 3) + (4 / 27) * (3 / 4) + (5 / 144) * (1 / 1))) : ℚ) = (625 / 5184) := by
  norm_num

theorem tree_12_b : (((12 / 25) * (1 / 324) + (32 / 225) * (81 / 1024) + (1 / 30) * (1 / 4) + (6 / 25) * (625 / 5184)) : ℚ) = 1 / 20 := by
  norm_num

theorem tree_13_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_13_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_13_stage_2 : ((((1 / 4) * (8 / 729))) : ℚ) = (2 / 729) := by
  norm_num

theorem tree_13_stage_3 : ((((-243 / 128) * (8 / 729) + (135 / 64) * (1 / 27))) : ℚ) = (11 / 192) := by
  norm_num

theorem tree_13_stage_4 : ((((27 / 4) * (8 / 729) + (-27 / 5) * (1 / 27) + (16 / 15) * (27 / 64))) : ℚ) = (35 / 108) := by
  norm_num

theorem tree_13_stage_5 : ((((-5 / 16) * (8 / 729) + (13 / 16) * (1 / 27) + (4 / 27) * (27 / 64) + (5 / 144) * (1 / 1))) : ℚ) = (1445 / 11664) := by
  norm_num

theorem tree_13_b : (((12 / 25) * (2 / 729) + (32 / 225) * (11 / 192) + (1 / 30) * (35 / 108) + (6 / 25) * (1445 / 11664)) : ℚ) = 1 / 20 := by
  norm_num

theorem tree_14_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_14_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_14_stage_2 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_14_stage_3 : ((((135 / 64) * (1 / 54))) : ℚ) = (5 / 128) := by
  norm_num

theorem tree_14_stage_4 : ((((-27 / 5) * (1 / 54) + (16 / 15) * (27 / 128))) : ℚ) = (1 / 8) := by
  norm_num

theorem tree_14_stage_5 : ((((13 / 16) * (1 / 54) + (4 / 27) * (27 / 128) + (5 / 144) * (1 / 2))) : ℚ) = (55 / 864) := by
  norm_num

theorem tree_14_b : (((32 / 225) * (5 / 128) + (1 / 30) * (1 / 8) + (6 / 25) * (55 / 864)) : ℚ) = 1 / 40 := by
  norm_num

theorem tree_15_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_15_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_15_stage_2 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_15_stage_3 : ((((135 / 64) * (1 / 81))) : ℚ) = (5 / 192) := by
  norm_num

theorem tree_15_stage_4 : ((((-27 / 5) * (1 / 81) + (16 / 15) * (9 / 64))) : ℚ) = (1 / 12) := by
  norm_num

theorem tree_15_stage_5 : ((((13 / 16) * (1 / 81) + (4 / 27) * (9 / 64) + (5 / 144) * (1 / 3))) : ℚ) = (55 / 1296) := by
  norm_num

theorem tree_15_b : (((32 / 225) * (5 / 192) + (1 / 30) * (1 / 12) + (6 / 25) * (55 / 1296)) : ℚ) = 1 / 60 := by
  norm_num

theorem tree_16_stage_0 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_16_stage_1 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_16_stage_2 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_16_stage_3 : (((0)) : ℚ) = (0 / 1) := by
  norm_num

theorem tree_16_stage_4 : ((((16 / 15) * (15 / 128))) : ℚ) = (1 / 8) := by
  norm_num

theorem tree_16_stage_5 : ((((4 / 27) * (15 / 128))) : ℚ) = (5 / 288) := by
  norm_num

theorem tree_16_b : (((1 / 30) * (1 / 8) + (6 / 25) * (5 / 288)) : ℚ) = 1 / 120 := by
  norm_num

theorem original_pd_time_defect : ((-55598247709687825063464852356873 / 324518553658426726783156020576256) : ℚ) < -(1 / 6) := by
  norm_num

end
end FindOrbIntegrator

#print axioms FindOrbIntegrator.solution_derivative
#print axioms FindOrbIntegrator.solution_initial
#print axioms FindOrbIntegrator.solution_endpoint
#print axioms FindOrbIntegrator.solution_nonzero
#print axioms FindOrbIntegrator.invisible_stage_0
#print axioms FindOrbIntegrator.invisible_stage_1
#print axioms FindOrbIntegrator.invisible_stage_2
#print axioms FindOrbIntegrator.invisible_stage_3
#print axioms FindOrbIntegrator.invisible_stage_4
#print axioms FindOrbIntegrator.invisible_stage_5
#print axioms FindOrbIntegrator.every_weighted_estimate_zero
#print axioms FindOrbIntegrator.tree_0_stage_0
#print axioms FindOrbIntegrator.tree_0_stage_1
#print axioms FindOrbIntegrator.tree_0_stage_2
#print axioms FindOrbIntegrator.tree_0_stage_3
#print axioms FindOrbIntegrator.tree_0_stage_4
#print axioms FindOrbIntegrator.tree_0_stage_5
#print axioms FindOrbIntegrator.tree_0_b
#print axioms FindOrbIntegrator.tree_0_bEmbedded
#print axioms FindOrbIntegrator.tree_1_stage_0
#print axioms FindOrbIntegrator.tree_1_stage_1
#print axioms FindOrbIntegrator.tree_1_stage_2
#print axioms FindOrbIntegrator.tree_1_stage_3
#print axioms FindOrbIntegrator.tree_1_stage_4
#print axioms FindOrbIntegrator.tree_1_stage_5
#print axioms FindOrbIntegrator.tree_1_b
#print axioms FindOrbIntegrator.tree_1_bEmbedded
#print axioms FindOrbIntegrator.tree_2_stage_0
#print axioms FindOrbIntegrator.tree_2_stage_1
#print axioms FindOrbIntegrator.tree_2_stage_2
#print axioms FindOrbIntegrator.tree_2_stage_3
#print axioms FindOrbIntegrator.tree_2_stage_4
#print axioms FindOrbIntegrator.tree_2_stage_5
#print axioms FindOrbIntegrator.tree_2_b
#print axioms FindOrbIntegrator.tree_2_bEmbedded
#print axioms FindOrbIntegrator.tree_3_stage_0
#print axioms FindOrbIntegrator.tree_3_stage_1
#print axioms FindOrbIntegrator.tree_3_stage_2
#print axioms FindOrbIntegrator.tree_3_stage_3
#print axioms FindOrbIntegrator.tree_3_stage_4
#print axioms FindOrbIntegrator.tree_3_stage_5
#print axioms FindOrbIntegrator.tree_3_b
#print axioms FindOrbIntegrator.tree_3_bEmbedded
#print axioms FindOrbIntegrator.tree_4_stage_0
#print axioms FindOrbIntegrator.tree_4_stage_1
#print axioms FindOrbIntegrator.tree_4_stage_2
#print axioms FindOrbIntegrator.tree_4_stage_3
#print axioms FindOrbIntegrator.tree_4_stage_4
#print axioms FindOrbIntegrator.tree_4_stage_5
#print axioms FindOrbIntegrator.tree_4_b
#print axioms FindOrbIntegrator.tree_4_bEmbedded
#print axioms FindOrbIntegrator.tree_5_stage_0
#print axioms FindOrbIntegrator.tree_5_stage_1
#print axioms FindOrbIntegrator.tree_5_stage_2
#print axioms FindOrbIntegrator.tree_5_stage_3
#print axioms FindOrbIntegrator.tree_5_stage_4
#print axioms FindOrbIntegrator.tree_5_stage_5
#print axioms FindOrbIntegrator.tree_5_b
#print axioms FindOrbIntegrator.tree_5_bEmbedded
#print axioms FindOrbIntegrator.tree_6_stage_0
#print axioms FindOrbIntegrator.tree_6_stage_1
#print axioms FindOrbIntegrator.tree_6_stage_2
#print axioms FindOrbIntegrator.tree_6_stage_3
#print axioms FindOrbIntegrator.tree_6_stage_4
#print axioms FindOrbIntegrator.tree_6_stage_5
#print axioms FindOrbIntegrator.tree_6_b
#print axioms FindOrbIntegrator.tree_6_bEmbedded
#print axioms FindOrbIntegrator.tree_7_stage_0
#print axioms FindOrbIntegrator.tree_7_stage_1
#print axioms FindOrbIntegrator.tree_7_stage_2
#print axioms FindOrbIntegrator.tree_7_stage_3
#print axioms FindOrbIntegrator.tree_7_stage_4
#print axioms FindOrbIntegrator.tree_7_stage_5
#print axioms FindOrbIntegrator.tree_7_b
#print axioms FindOrbIntegrator.tree_7_bEmbedded
#print axioms FindOrbIntegrator.tree_8_stage_0
#print axioms FindOrbIntegrator.tree_8_stage_1
#print axioms FindOrbIntegrator.tree_8_stage_2
#print axioms FindOrbIntegrator.tree_8_stage_3
#print axioms FindOrbIntegrator.tree_8_stage_4
#print axioms FindOrbIntegrator.tree_8_stage_5
#print axioms FindOrbIntegrator.tree_8_b
#print axioms FindOrbIntegrator.tree_9_stage_0
#print axioms FindOrbIntegrator.tree_9_stage_1
#print axioms FindOrbIntegrator.tree_9_stage_2
#print axioms FindOrbIntegrator.tree_9_stage_3
#print axioms FindOrbIntegrator.tree_9_stage_4
#print axioms FindOrbIntegrator.tree_9_stage_5
#print axioms FindOrbIntegrator.tree_9_b
#print axioms FindOrbIntegrator.tree_10_stage_0
#print axioms FindOrbIntegrator.tree_10_stage_1
#print axioms FindOrbIntegrator.tree_10_stage_2
#print axioms FindOrbIntegrator.tree_10_stage_3
#print axioms FindOrbIntegrator.tree_10_stage_4
#print axioms FindOrbIntegrator.tree_10_stage_5
#print axioms FindOrbIntegrator.tree_10_b
#print axioms FindOrbIntegrator.tree_11_stage_0
#print axioms FindOrbIntegrator.tree_11_stage_1
#print axioms FindOrbIntegrator.tree_11_stage_2
#print axioms FindOrbIntegrator.tree_11_stage_3
#print axioms FindOrbIntegrator.tree_11_stage_4
#print axioms FindOrbIntegrator.tree_11_stage_5
#print axioms FindOrbIntegrator.tree_11_b
#print axioms FindOrbIntegrator.tree_12_stage_0
#print axioms FindOrbIntegrator.tree_12_stage_1
#print axioms FindOrbIntegrator.tree_12_stage_2
#print axioms FindOrbIntegrator.tree_12_stage_3
#print axioms FindOrbIntegrator.tree_12_stage_4
#print axioms FindOrbIntegrator.tree_12_stage_5
#print axioms FindOrbIntegrator.tree_12_b
#print axioms FindOrbIntegrator.tree_13_stage_0
#print axioms FindOrbIntegrator.tree_13_stage_1
#print axioms FindOrbIntegrator.tree_13_stage_2
#print axioms FindOrbIntegrator.tree_13_stage_3
#print axioms FindOrbIntegrator.tree_13_stage_4
#print axioms FindOrbIntegrator.tree_13_stage_5
#print axioms FindOrbIntegrator.tree_13_b
#print axioms FindOrbIntegrator.tree_14_stage_0
#print axioms FindOrbIntegrator.tree_14_stage_1
#print axioms FindOrbIntegrator.tree_14_stage_2
#print axioms FindOrbIntegrator.tree_14_stage_3
#print axioms FindOrbIntegrator.tree_14_stage_4
#print axioms FindOrbIntegrator.tree_14_stage_5
#print axioms FindOrbIntegrator.tree_14_b
#print axioms FindOrbIntegrator.tree_15_stage_0
#print axioms FindOrbIntegrator.tree_15_stage_1
#print axioms FindOrbIntegrator.tree_15_stage_2
#print axioms FindOrbIntegrator.tree_15_stage_3
#print axioms FindOrbIntegrator.tree_15_stage_4
#print axioms FindOrbIntegrator.tree_15_stage_5
#print axioms FindOrbIntegrator.tree_15_b
#print axioms FindOrbIntegrator.tree_16_stage_0
#print axioms FindOrbIntegrator.tree_16_stage_1
#print axioms FindOrbIntegrator.tree_16_stage_2
#print axioms FindOrbIntegrator.tree_16_stage_3
#print axioms FindOrbIntegrator.tree_16_stage_4
#print axioms FindOrbIntegrator.tree_16_stage_5
#print axioms FindOrbIntegrator.tree_16_b
#print axioms FindOrbIntegrator.original_pd_time_defect
