#!/usr/bin/env node
// SPDX-License-Identifier: GPL-2.0-or-later
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const json=async path=>JSON.parse(await readFile(path,'utf8'));
const [paired,data,proofs,wide,origin,beforeNatural,afterNatural]=await Promise.all([
  json('results/paired.json'),json('results/dataset.json'),json('verification/evidence/proofs.json'),
  json('verification/evidence/wide-multiply-proofs.json'),json('provenance.json'),
  json('results/baseline-natural.json'),json('results/final-natural.json'),
]);
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>value.toLocaleString('en-US');
const ms=value=>value.toFixed(value<100?2:1);
const labels={'short-arc-fit':'Short-arc fit','ceres-30d':'Ceres: 30-day propagation','ceres-topocentric':'Ceres: topocentric predictions',
  'eccentricity-0.95':'High eccentricity (0.95)','eccentricity-0.999999':'Near-parabolic (0.999999)','eccentricity-1.4':'Hyperbolic retrograde (1.4)','ceres-heldout-fit':'Ceres: held-out recovery fit'};
const rows=paired.cases.map(c=>`<tr><th scope="row">${escape(labels[c.id]||c.id)}</th><td>${ms(c.engines['native-original'].phases.totalMs.median)}</td><td>${ms(c.engines.before.phases.totalMs.median)}</td><td>${ms(c.engines.after.phases.totalMs.median)}</td><td>${c.pairedSpeedup.median.toFixed(2)}×</td><td>${c.pairedSpeedup.min.toFixed(2)}–${c.pairedSpeedup.max.toFixed(2)}×</td></tr>`).join('');
const naturalCell=phase=>`${ms(phase.median)}<br><small>${ms(phase.min)}–${ms(phase.max)}</small>`;
const naturalRows=afterNatural.cases.map(c=>{
  const before=beforeNatural.cases.find(b=>b.id===c.id).engines.wasm.phases.totalMs;
  const after=c.engines.wasm.phases.totalMs;
  return `<tr><th scope="row">${escape(labels[c.id]||c.id)}</th><td>${ms(c.engines['native-original'].phases.totalMs.median)}</td><td>${naturalCell(before)}</td><td>${naturalCell(after)}</td><td>${(before.median/after.median).toFixed(2)}×</td></tr>`;
}).join('');
const propagationRatios=afterNatural.cases.filter(c=>!c.id.endsWith('-fit')).map(c=>beforeNatural.cases.find(b=>b.id===c.id).engines.wasm.phases.totalMs.median/c.engines.wasm.phases.totalMs.median);
const naturalPerformance=`<p><strong>Propagation improved by ${Math.min(...propagationRatios).toFixed(2)}–${Math.max(...propagationRatios).toFixed(2)}× in this run; fitting was essentially unchanged.</strong> The shipped optimizations reduce command setup and retain compiled code. They do not change the orbital integrator.</p><h3>Ordinary garbage collection</h3><div class="table-wrap"><table><thead><tr><th scope="col">Workload</th><th scope="col">Native original<br>ms</th><th scope="col">Original WASM<br>ms / range</th><th scope="col">Current WASM<br>ms / range</th><th scope="col">Median ratio</th></tr></thead><tbody>${naturalRows}</tbody></table></div><p class="muted">${escape(afterNatural.host.cpu)} · ${escape(afterNatural.host.arch)} · Node ${escape(afterNatural.host.node)}. Original and current ports ran in separate processes with natural garbage collection: ${afterNatural.methodology.warmup} warmups and ${afterNatural.methodology.repetitions} measured repetitions per case. Ratios compare independent medians. Small text gives observed min–max, not a confidence interval. The baseline process ran first; host drift is not eliminated. The WASM runs use the full 110 MB pack. Native totals include process launch and private reference-file setup. Network download, browser worker transfer, and one-time verification/compilation are outside these command timings. <a href="../results/baseline-natural.json">Original samples</a> · <a href="../results/final-natural.json">Current samples and setup costs</a> · <a href="../results/final-natural-comparison.json">Numerical comparison</a>.</p><h3>Controlled garbage collection: diagnostic costs</h3><p>These additional runs force collection before each command and record its cost separately. They expose module-recompilation costs after collection and avoid charging one variant for the previous variant's garbage. They are not ordinary browser latency measurements.</p>`;
const maxHorizons=Math.max(...data.wasm.cases.flatMap(c=>c.accuracy.horizonsPositionErrorMeters||[]));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Find_Orb WASM — findings and measurements</title><style>
:root{color-scheme:light;--ink:#192c37;--muted:#4d6270;--line:#cedadf;--accent:#075f60}*{box-sizing:border-box}body{margin:0;background:#eef3f4;color:var(--ink);font:16px/1.6 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:40px 24px}header{border-bottom:2px solid var(--accent);padding-bottom:22px}h1{font-size:clamp(1.9rem,4vw,3rem);line-height:1.15;margin:8px 0 18px}h2{font-size:1.4rem;margin:0 0 16px}h3{font-size:1.05rem;margin-bottom:6px}p{max-width:88ch}.eyebrow{color:var(--accent);font-weight:700;letter-spacing:.08em;text-transform:uppercase;font-size:.8rem}.muted,small{color:var(--muted)}a{color:#075b87;text-underline-offset:3px}nav{display:flex;gap:22px;flex-wrap:wrap;margin-top:20px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.card,section{background:white;border:1px solid var(--line);border-radius:10px;padding:22px}section{margin:22px 0}.metric{font-size:2.1rem;font-weight:750;line-height:1.2;display:block;color:var(--accent)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.92rem}th,td{text-align:right;padding:12px 10px;border-bottom:1px solid var(--line);white-space:nowrap}th:first-child{text-align:left;white-space:normal}thead{background:#eff6f6}.note{border-left:4px solid var(--accent);padding:8px 16px;background:#edf6f5}.split{display:grid;grid-template-columns:1fr 1fr;gap:22px}.tag{font-size:.78rem;background:#e8f2f0;border:1px solid #c4dbd6;border-radius:3px;padding:2px 7px;font-weight:650}.bar{height:18px;background:#dce8eb;border-radius:3px;margin:5px 0 16px;overflow:hidden}.bar span{display:block;height:100%;background:var(--accent)}code{overflow-wrap:anywhere;font-size:.88em}footer{color:var(--muted);font-size:.88rem;margin:30px 0}@media(max-width:700px){main{padding:24px 14px}.cards,.split{grid-template-columns:1fr}section{padding:18px}}@media print{body{background:white}main{padding:0}.cards,section{break-inside:avoid}nav{display:none}a{color:inherit}.table-wrap{overflow:visible}th,td{white-space:normal;padding:6px}h1{font-size:28px}}
</style></head><body><main><header><div class="eyebrow">Independent Project Pluto port · measured ${escape(paired.createdAt.slice(0,10))}</div><h1>Find_Orb WebAssembly</h1><p>The standalone repository preserves the original solver and its licenses, adds targeted mathematical and compiler checks, measures native and WASM execution, and offers a compact data download with verified automatic loading.</p><nav aria-label="Report sections"><a href="#performance">Performance</a><a href="#accuracy">Correctness</a><a href="#data">Compact data</a><a href="#builds">Reproducibility</a></nav></header>
<div class="cards"><article class="card"><span class="metric">${(data.sizes.compactPack.gzip9/1e6).toFixed(2)} MB</span>Complete compact pack, gzip<br><small>${data.transportReductionPercent.toFixed(1)}% smaller than full-pack gzip</small></article><article class="card"><span class="metric">7 / 7</span>Scientific workloads passed<br><small>Independent Horizons and native comparisons</small></article><article class="card"><span class="metric">${proofs.obligations.length} + ${wide.obligations.length}</span>Targeted SMT obligations passed<br><small>Port checks + experimental integer helper</small></article></div>
<section id="performance"><h2>Measured performance</h2><p>Copy-on-write reference mounting avoids copying the full 110 MB pack for every fresh command. The session also retains immutable compiled code, avoiding repeated compilation work after garbage collection. Each job receives independent C globals, heap, filesystem, and random state. Both changes preserve orbital arithmetic.</p><div class="table-wrap"><table><thead><tr><th scope="col">Workload</th><th scope="col">Native original<br>ms</th><th scope="col">Original WASM<br>ms</th><th scope="col">Current WASM<br>ms</th><th scope="col">Paired speedup</th><th scope="col">Observed spread</th></tr></thead><tbody>${rows}</tbody></table></div><p class="muted">${escape(paired.host.cpu)} · ${escape(paired.host.arch)} · Node ${escape(paired.host.node)}. ${paired.methodology.warmup} warmups and ${paired.methodology.repetitions} measured repetitions, alternating before/after order. Times are medians; speedups are medians of paired ratios. Spread is min–max, not a confidence interval. Pack verification and network/worker startup are measured separately or excluded. Native totals include process launch and private data-file setup. See <a href="../results/paired.json">all samples, outputs, manifests, and native count-matched results</a>.</p><p class="note">${escape(paired.methodology.garbageCollection)} Controlled garbage collection is a diagnostic of isolated command costs. It is not a promise about ordinary browser latency. The report retains separate natural-GC observations and the original uncontrolled paired run.</p><div class="note">Native ARM <code>long double</code> has 53 significand bits; WASM has 113. Software binary128 arithmetic dominates the fitting workload. The port retains that precision, so native and WASM timing includes different extended-precision costs.</div><div class="split"><article><h3>Link-time optimization <span class="tag">Rejected</span></h3><p>Accuracy checks passed, but exploratory fitting runs were slower and the binary was larger. The default build does not enable LTO. <a href="../results/lto-exploratory.json">Measurements</a>.</p></article><article><h3>Exact integer multiplication <span class="tag">Experimental</span></h3><p>An exact limb-based replacement for compiler-rt multiplication has ${wide.obligations.length} proof obligations and independent integer/IEEE tests, including one million random binary128 products. It did not yield a reliable end-to-end fitting gain, so the shipped solver keeps the original runtime implementation. <a href="../results/quad-differential.json">Differential evidence</a> and <a href="../results/quad-exploratory.json">solver measurements</a>.</p></article></div></section>
<section id="accuracy"><h2>What correctness evidence establishes</h2><div class="split"><article><h3>Mathematical and compiler checks</h3><p>Source-anchored SMT obligations cover search bounds, termination and insertion semantics; exact-real vector identities; floating-point reassociation/contraction counterexamples; and DE440 record-selection equivalence. The experimental helper has a separate source contract and exact-product proof.</p><p>Actual extracted routines pass 21,229 search and 50,121 vector cases across native O0/O3/sanitized and WASM O0/O3 builds. The compiler audit checks relaxed floating-point flags and ABI differences.</p></article><article><h3>Astronomical and port checks</h3><p>The seven workloads cover a short-arc fit with wide uncertainty, Ceres propagation/topocentric predictions and held-out recovery, plus high-eccentricity, near-parabolic, and hyperbolic retrograde trajectories. Ceres's maximum 30-day position error against the stored independent Horizons reference was ${maxHorizons.toFixed(2)} metres.</p><p>Native propagation must agree within 1 metre and 10 μm/s; independent sky predictions and held-out recovery must meet 0.1 arcsecond tolerances. Short-arc fitting retains observations and broad uncertainty.</p></article></div><div class="note">These are targeted guarantees and empirical checks. They do not prove the full integrator, nonlinear fit, covariance calibration, compiler pipeline, or browser engine correct. Mathematical models still require reviewed correspondence to source; SMT results have not been independently proof-kernel checked.</div><p><a href="verification.html">Full verification scope, trusted base, and primary references</a> · <a href="../verification/evidence/">Replayable proof evidence</a> · <a href="../benchmark/README.md">Reproduce accuracy and benchmarks</a>.</p></section>
<section id="data"><h2>6.33 MB download, with original coefficients</h2><p>The default pack retains every auxiliary file and selects complete DE440 records for 2000–2040 plus boundary margins. No coefficients, physical constants, bodies, or sky-brightness data are approximated or discarded.</p><label>Full data pack, gzip: ${(data.sizes.fullPack.gzip9/1e6).toFixed(2)} MB</label><div class="bar" aria-hidden="true"><span style="width:100%"></span></div><label>Compact pack, gzip: ${(data.sizes.compactPack.gzip9/1e6).toFixed(2)} MB</label><div class="bar" aria-hidden="true"><span style="width:${(100*data.sizes.compactPack.gzip9/data.sizes.fullPack.gzip9).toFixed(2)}%"></span></div><p><strong>${number(data.native.bitwiseEqualComponents)} native components matched bit-for-bit</strong> at ${number(data.native.epochs)} epochs, covering record boundaries and adjacent floating-point values, all reader target codes, centres, and position/velocity modes. All seven complete WASM workloads also match scientific output exactly after excluding wall-clock metadata.</p><p>The actual ephemeris interval is <strong>(1999-11-22, 2040-02-08]</strong> in the ephemeris time scale. All intermediate integration and light-time queries must remain inside it. Missing data, read failures, and out-of-range queries reject the job; rough analytic fallback is disabled. Historical workloads can use a wider or full pack.</p><p><code>createSessionFromUrls()</code> verifies the worker and bounded decompressed data, then initializes the session without a file chooser. Real Chromium tests cover repeated accurate computation, cancellation, and a cross-origin CDN that hides its gzip header. First-use offline operation still needs application packaging or caching.</p><p><a href="dataset.html">Dataset analysis</a> · <a href="../results/dataset.json">Exactness, guard, and size evidence</a> · <a href="../README.md">Build and API examples</a>.</p></section>
<section id="builds"><h2>Provenance and redistribution</h2><p>Extracted from <a href="${escape(origin.sourceRepository)}/commit/${escape(origin.sourceCommit)}">webastrometrica ${escape(origin.sourceCommit.slice(0,7))}</a>, its latest <code>origin/main</code> when extraction began. Initial standalone commit: <code>fe8a88d</code>. <a href="../provenance.json">Original file hashes</a> are retained.</p><p>Builds use pinned sources and Emscripten, fresh checked source and library trees, and an explicit floating-point policy that ambient compiler flags cannot override. The corresponding-source archive includes upstream code and build recipes; its offline-source rebuild reproduced the same WASM and data hashes. <a href="../results/source-rebuild.json">Rebuild evidence</a> and <a href="../results/build-integrity.json">contaminated-environment check</a>.</p><p>Original solver: <a href="https://github.com/Bill-Gray/find_orb">Bill Gray / Project Pluto Find_Orb</a>. Find_Orb and port additions are GPL-2.0-or-later; dependency notices are preserved individually, and combined solver distributions use GPLv3. Retain the corresponding source and complete notices with binaries. See <a href="../NOTICE">NOTICE</a> and <a href="../licenses/">license texts</a>.</p></section>
<section><h2>Useful next research</h2><p>Expand whole-program sanitizer coverage and difficult close-encounter/ill-conditioned cases, measure additional browsers and architectures, and investigate certified mixed-precision integration only with explicit error bounds and a reliable high-precision fallback. The measured fitting bottleneck will need work of that kind for a large speedup; lowering precision without such evidence is not part of this port.</p></section><footer>Independent experimental port, not an official Project Pluto release. Reports preserve limitations alongside the measurements. Generated from checked-in JSON evidence by <code>scripts/report.mjs</code>.</footer></main></body></html>`;
const finalHTML=html.replace('Both changes preserve orbital arithmetic.</p><div class="table-wrap">',
  'Both changes preserve orbital arithmetic.</p>'+naturalPerformance+'<div class="table-wrap">');
await mkdir('docs',{recursive:true});await writeFile('docs/findings.html',finalHTML);console.log('Wrote docs/findings.html');
